# Generated by Django 5.2 on 2025-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varitations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varitations',
            new_name='variation',
        ),
    ]
